# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bijection Vector
#'
#' @param K number of levels
#' @return A \code{vec} with length \eqn{K}.
bijectionvector <- function(K) {
    .Call('ecdm_bijectionvector', PACKAGE = 'ecdm', K)
}

#' Inverse Bijection Vector
#'
#' @param CL A \code{double} that controls ...
#' @inheritParams bijectionvector
#' @return A \code{vec} with length \eqn{K}.
inv_bijectionvector <- function(K, CL) {
    .Call('ecdm_inv_bijectionvector', PACKAGE = 'ecdm', K, CL)
}

#' \eqn{\eta} Matrix
#'
#' @param K      Number of Attribute Levels
#' @param J      Number of Assessment Items
#' @param Q      Q Matrix with dimensions \eqn{K \times J}{K x J}.
#' @return A `mat` with dimensions \eqn{J \times 2^K}{J x 2^K}.
ETAmat <- function(K, J, Q) {
    .Call('ecdm_ETAmat', PACKAGE = 'ecdm', K, J, Q)
}

#' \eqn{\eta} Matrix
#'
#' @param K      Number of Attribute Levels
#' @return A `cube` with dimensions \eqn{K \times 2^{K-1} \times 2^K}{J x 2^{K-1} x 2^K}.
ETAmat_nok <- function(K) {
    .Call('ecdm_ETAmat_nok', PACKAGE = 'ecdm', K)
}

#' \eqn{\eta} Matrix \eqn{1-\alpha_{ck}}
#'
#' @param K      Number of Attribute Levels
#' @return A `cube` with dimensions \eqn{K \times 2^{K-1} \times 2^K}{J x 2^{K-1} x 2^K}.
ETAmat_nok_one_m_ac <- function(K) {
    .Call('ecdm_ETAmat_nok_one_m_ac', PACKAGE = 'ecdm', K)
}

#' Count AB (Old Version)
#'
#' What is AB? Number of attributes possessed by the individual?
#' @param K    Number of Attributes as \code{unsigned int}.
#' @param k    Present attribute level as \code{unsigned int}.
#' @param qj   \eqn{j}th row of the \eqn{Q} matrix.
#' @param Yj    Binary responses for individual \eqn{i} in the form of \code{vec}
#' @param alpha Attribute profile as a \code{mat}.
abcount_old <- function(K, k, qj, Yj, alpha) {
    .Call('ecdm_abcount_old', PACKAGE = 'ecdm', K, k, qj, Yj, alpha)
}

#' Count AB
#'
#' What is AB? Number of attributes possessed by the individual?
#' @param N              Number of Observations given as `unsigned int`.
#' @param Yj             Binary responses for individual \eqn{i} in the form of `vec`
#' @param CLASS          Does the individual possess all the necessary attributes? (1 or 0)
#' @param ETAtnokimes1ma something?
#' @return A `vec` containing the counts of AB parameters of the IRT
abcounts <- function(N, Yj, CLASS, ETAtnokimes1ma) {
    .Call('ecdm_abcounts', PACKAGE = 'ecdm', N, Yj, CLASS, ETAtnokimes1ma)
}

#' Classification Matrix by Q Matrix
#'
#' Construct a classification matrix by Q Matrix
#' @param K Number of Attribute Levels as an `unsigned integer`.
#' @return A `mat`.
ClassbyQmat <- function(K) {
    .Call('ecdm_ClassbyQmat', PACKAGE = 'ecdm', K)
}

#' Log likelihood associated with assessment item \eqn{j}.
#'
#' @param N      Number of Observations
#' @param Yj     Binary responses to assessements in `vec` form with length \eqn{N}.
#' @param ETAj   \eqn{\eta_j} in `vec` form of length \eqn{2^k}.
#' @param CLASS  Does the individual possess all the necessary attributes?
#' @param gj     Guessing value
#' @param sj     Slipping Value
#' @return A `double` containing the log likelihood
llj <- function(N, Yj, ETAj, CLASS, gj, sj) {
    .Call('ecdm_llj', PACKAGE = 'ecdm', N, Yj, ETAj, CLASS, gj, sj)
}

#' Likelihood Function for DINA
#'
#' Compute the Likelihood Function for DINA
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param Y      Binary responses to assessements in `matrix` form with
#'               dimensions \eqn{N \times J}{N x J}.
#' @param ETA    Q Matrix with dimensions \eqn{K x J}.
#' @param CLASS  Does the individual possess all the necessary attributes?
#' @param pis    Latent Class Probabilities with length \eqn{K}
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
lnlik_dina_condclass <- function(N, J, Y, ETA, CLASS, pis, gs, ss) {
    .Call('ecdm_lnlik_dina_condclass', PACKAGE = 'ecdm', N, J, Y, ETA, CLASS, pis, gs, ss)
}

#' Probability for Equation 1?
pYjeq1 <- function(ETAbyQ, pis, nClass, sj, gj) {
    .Call('ecdm_pYjeq1', PACKAGE = 'ecdm', ETAbyQ, pis, nClass, sj, gj)
}

#' Probability...
pYit <- function(ETA_it, Y_it, ss, gs) {
    .Call('ecdm_pYit', PACKAGE = 'ecdm', ETA_it, Y_it, ss, gs)
}

#' Compute Likelihood for DINA
#'
#' Calculates the likelihood for the DINA model
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param nClass Number of Classes typically \eqn{2^K}.
#' @param Y      Binary responses to assessements in `matrix` form with
#'               dimensions \eqn{N \times J}{N x J}.
#' @param ETA    Q Matrix with dimensions \eqn{K x J}.
#' @param pis    Latent Class Probabilities with length \eqn{K}
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @return The likelihood in `double` form.
lnlik_dina <- function(N, J, nClass, Y, ETA, pis, gs, ss) {
    .Call('ecdm_lnlik_dina', PACKAGE = 'ecdm', N, J, nClass, Y, ETA, pis, gs, ss)
}

#' Generate a Random Q Matrix
#'
#' Randomly construct a Q Matrix given dimensions
#' @param J Number of Assessment Items as an `unsigned integer`.
#' @param K Number of Attribute Levels as an `unsigned integer`.
#' @return A `mat`.
random_Q <- function(J, K) {
    .Call('ecdm_random_Q', PACKAGE = 'ecdm', J, K)
}

#' Verify Q Matrix is Identifiable
#'
#' Performs a check to see if Q is identifable or not.
#' @param Q The Q matrix to be checked with dimensions \eqn{K \times J}{K x J}.
#' @return A double with value either: 0 or 1
identify_check <- function(Q) {
    .Call('ecdm_identify_check', PACKAGE = 'ecdm', Q)
}

#' Update the Q
#'
#' Updation step for DINA
#' @param Q     Q Matrix with dimensions \eqn{K x J}.
#' @param Y     Binary responses to assessements in \code{matrix} form with
#'              dimensions \eqn{N \times J}{N x J}.
#' @param alpha Profile Matrix
#' @param ss    A \code{vec} describing the probability of slipping or
#'              the probability of an incorrect response for individuals with
#'              all of the required attributes
#' @param gs    A \code{vec} describing the probability of guessing or
#'              the probability subject correctly answers item \eqn{j} when at
#'              least one attribute is lacking.
updateQ_DINA <- function(Q, Y, alpha, ss, gs) {
    invisible(.Call('ecdm_updateQ_DINA', PACKAGE = 'ecdm', Q, Y, alpha, ss, gs))
}

#' Simulate Binary Responses for DINA Model
#'
#' Calculates the Odds Ratio
#' @param N         Number of Observations
#' @param J         Number of Assessment Items
#' @param K         Number of Attribute Levels as an `unsigned integer`.
#' @param Q         Q Matrix with dimensions \eqn{K x J}.
#' @param Y         Binary responses to assessements in \code{matrix} form with
#'                  dimensions \eqn{N \times J}{N x J}.
#' @param CLASS     Does the individual possess all the necessary attributes?
#' @param ss        A `vec` describing the probability of slipping or
#'                  the probability of an incorrect response for individuals
#'                  with all of the required attributes
#' @param gs        A `vec` describing the probability of guessing or
#'                  the probability subject correctly answers item \eqn{j} when
#'                  at least one attribute is lacking.
#' @param vj        A `vec` containing the powers of 2.
#' @param ETAmatnok A variant on the \eqn{\eta} Matrix.
#' @param a_by_q    Classification Matrix by a \eqn{Q} Matrix.
#' @param vv        Bijection vector with respect to \eqn{K}.
#' @details
#' No return is done here as the update is done by reference.
updateQ_DINA_new <- function(N, K, J, Q, Y, CLASS, ss, gs, vj, ETAmatnok, a_by_q, vv) {
    invisible(.Call('ecdm_updateQ_DINA_new', PACKAGE = 'ecdm', N, K, J, Q, Y, CLASS, ss, gs, vj, ETAmatnok, a_by_q, vv))
}

#' Condition Threshold
#' @param k         Present attribute level as `unsigned int`.
#' @param j         Present assessment items as `unsigned int`.
#' @param n_noks    Number of n okay observations?
#' @param N         Number of Assessment Items
#' @param K         Number of Observations
#' @param Yj        Number of Observations
#' @param CLASS     Does the individual possess all the necessary attributes?
#' @param ETA       Alpha profile matrix.
#' @param gj        The probability of guessing or the probability subject
#'                  correctly answers item \eqn{j} when at least one attribute
#'                  is lacking.
#' @param sj        The probability of slipping or the probability of an
#'                  incorrect response for individuals with all of the required
#'                  attributes
#' @param ETAmatnok A variant on the \eqn{\eta} matrix.
#' @return A `double` indicating the conditional threshold.
cond_threshold <- function(k, j, n_noks, N, K, Yj, CLASS, Q, gj, sj, ETAmatnok) {
    .Call('ecdm_cond_threshold', PACKAGE = 'ecdm', k, j, n_noks, N, K, Yj, CLASS, Q, gj, sj, ETAmatnok)
}

#' Simulate Binary Responses for DINA Model
#'
#' Calculates the Odds Ratio
#' @param N     Number of Observations
#' @param J     Number of Assessment Items
#' @param CLASS Does the individual possess all the necessary attributes?
#' @param ETA   \eqn{\eta} Matrix containing indicators.
#' @param gs    A `vec` describing the probability of guessing or
#'              the probability subject correctly answers item \eqn{j} when at
#'              least one attribute is lacking.
#' @param ss    A `vec` describing the probability of slipping or
#'              the probability of an incorrect response for individuals with
#'              all of the required attributes
#' @return A `mat`
sim_Y_dina <- function(N, J, CLASS, ETA, gs, ss) {
    .Call('ecdm_sim_Y_dina', PACKAGE = 'ecdm', N, J, CLASS, ETA, gs, ss)
}

#' Update the Parameters
#'
#' Perform a parameter update
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param K      Number of Attribute Levels
#' @param nClass Number of classes?
#' @param Y      A `matrix` with dimensions \eqn{N \times J}{N x J} containing
#'               the binary responses to assessements.
#' @param ETA    Alpha profile matrix.
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @param CLASS  Does the individual possess all the necessary attributes? (1 or 0)
#' @param pis    Latent Class Probabilities with length \eqn{K}
parm_update_nomiss <- function(N, J, K, nClass, Y, ETA, gs, ss, CLASS, pis) {
    invisible(.Call('ecdm_parm_update_nomiss', PACKAGE = 'ecdm', N, J, K, nClass, Y, ETA, gs, ss, CLASS, pis))
}

#' Compute the Odds Ratio
#'
#' Calculates the Odds Ratio
#' @param N  Number of Observations
#' @param J  Number of Assessment Items
#' @param Yt Estimated binary responses to assessements in \code{matrix} form
#'           with dimensions \eqn{N \times J}{N x J}.
#' @return A `matrix`.
OddsRatio <- function(N, J, Yt) {
    .Call('ecdm_OddsRatio', PACKAGE = 'ecdm', N, J, Yt)
}

#' Exploratory Determinatistic Input, Noise and Gate Model (EDINA)
#'
#' Compute the EDINA model
#' @param Y      Binary responses to assessements in \code{matrix} form with
#'               dimensions \eqn{N \times J}{N x J}.
#' @param K      Number of Attribute Levels as an \code{unsigned integer}.
#' @param burnin Number of Observations to discard on the chain.
#' @param chain_length Length of the MCMC chain
#' @return
#' A `list` containing:
#' - **GS**: Guessing
#' - **SS**: Slipping
#' - **PIs**: Latent Class Probabilities with length \eqn{K}
#' - **QS**: Q matrix
#' - **ORs**: Odds Ratio
dina_Gibbs_Q <- function(Y, K, burnin, chain_length = 10000L) {
    .Call('ecdm_dina_Gibbs_Q', PACKAGE = 'ecdm', Y, K, burnin, chain_length)
}

#' @title Generate Multinomial Random Variable
#' @description Sample a multinomial random variable for given probabilities.
#' @usage rmultinomial(ps)
#' @param ps A \code{vector} for the probability of each category.
#' @return A \code{vector} from a multinomial with probability ps.
#' @author Steven Andrew Culpepper
rmultinomial <- function(ps) {
    .Call('ecdm_rmultinomial', PACKAGE = 'ecdm', ps)
}

#' @title Generate Dirichlet Random Variable
#' @description Sample a Dirichlet random variable.
#' @usage rDirichlet(deltas)
#' @param deltas A \code{vector} of Dirichlet parameters.
#' @return A \code{vector} from a Dirichlet.
#' @author Steven Andrew Culpepper
rDirichlet <- function(deltas) {
    .Call('ecdm_rDirichlet', PACKAGE = 'ecdm', deltas)
}

