# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate ideal response \eqn{\eta} Matrix
#'
#' Creates the ideal response matrix for each trait
#'
#' @param K      Number of Attribute Levels
#' @param J      Number of Assessment Items
#' @param Q      Q Matrix with dimensions \eqn{K \times J}{K x J}.
#' @return A `mat` with dimensions \eqn{J \times 2^K}{J x 2^K}.
#' @noRd
NULL

#' \eqn{\eta} Matrix
#'
#' @param K      Number of Attribute Levels
#' @return A `cube` with dimensions
#'            \eqn{K \times 2^{K-1} \times 2^K}{J x 2^{K-1} x 2^K}.
#' @noRd
NULL

#' \eqn{\eta} Matrix \eqn{1-\alpha_{ck}}
#'
#' @param K      Number of Attribute Levels
#' @return A `cube` with dimensions
#'         \eqn{K \times 2^{K-1} \times 2^K}{J x 2^{K-1} x 2^K}.
#' @export
#' @noRd
NULL

#' Count AB (Old Version)
#'
#' What is AB? Number of attributes possessed by the individual?
#' @param K    Number of Attributes as \code{unsigned int}.
#' @param k    Present attribute level as \code{unsigned int}.
#' @param qj   \eqn{j}th row of the \eqn{Q} matrix.
#' @param Yj    Binary responses for individual \eqn{i} in the form of \code{vec}
#' @param alpha Attribute profile as a \code{mat}. ' @export
#' @noRd
NULL

#' Count AB
#'
#' What is AB? Number of attributes possessed by the individual?
#' @param N              Number of Observations given as `unsigned int`.
#' @param Yj             Binary responses for individual \eqn{i} in the form of
#'                       `vec`
#' @param CLASS          Does the individual possess all the necessary
#'                       attributes? (1 or 0)
#' @param ETAtnokimes1ma something?
#' @return A `vec` containing the counts of AB parameters of the IRT
#' @noRd
NULL

#' Log likelihood associated with assessment item \eqn{j}.
#'
#' @param N      Number of Observations
#' @param Yj     Binary responses to assessements in `vec` form with length
#'               \eqn{N}.
#' @param ETAj   \eqn{\eta_j} in `vec` form of length \eqn{2^k}.
#' @param CLASS  Does the individual possess all the necessary attributes?
#' @param gj     Guessing value
#' @param sj     Slipping Value
#' @return A `double` containing the log likelihood
#' @noRd
NULL

#' Likelihood Function for DINA
#'
#' Compute the Likelihood Function for DINA
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param Y      Binary responses to assessements in `matrix` form with
#'               dimensions \eqn{N \times J}{N x J}.
#' @param ETA    \eqn{\eta} Matrix with dimensions \eqn{J \times 2^K}{J x 2^K}.
#' @param CLASS  Does the individual possess all the necessary attributes?
#' @param pis    Latent Class Probabilities with length \eqn{K}
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @noRd
NULL

#' Probability for Equation 1?
#'
#' Compute a probability
#' @param ETAbyQ Column vectrom from ETAbyQ matrix.
#' @param pis    Latent Class Probabilities with length \eqn{2^K}
#' @param nClass Classification number
#' @param gj     Guessing value
#' @param sj     Slipping Value
#' @details
#' Not used in source
#' @noRd
NULL

#' Probability of Y
#'
#' New way to compute probability per it
#' @param ETA_it A column from the \eqn{\eta} matrix  with
#'               length \eqn{J}.
#' @param Y_it   Binary responses to assessements in `vec` form with
#'               length \eqn{J}.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @noRd
NULL

#' Compute Likelihood for DINA
#'
#' Calculates the likelihood for the DINA model
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param nClass Number of Classes typically \eqn{2^K}.
#' @param Y      Binary responses to assessements in `matrix` form with
#'               dimensions \eqn{N \times J}{N x J}.
#' @param ETA    \eqn{\eta} Matrix with dimensions \eqn{J \times 2^K}{J x 2^K}.
#' @param pis    Latent Class Probabilities with length \eqn{K}
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @return The likelihood in `double` form.
#' @noRd
NULL

#' Update the Q
#'
#' Updation step for DINA
#' @param Q     Q Matrix with dimensions \eqn{J x K}.
#' @param Y     Binary responses to assessements in \code{matrix} form with
#'              dimensions \eqn{N \times J}{N x J}.
#' @param alpha Profile Matrix
#' @param ss    A \code{vec} describing the probability of slipping or
#'              the probability of an incorrect response for individuals with
#'              all of the required attributes
#' @param gs    A \code{vec} describing the probability of guessing or
#'              the probability subject correctly answers item \eqn{j} when at
#'              least one attribute is lacking.
#' @noRd
NULL

#' Simulate Binary Responses for DINA Model
#'
#' Calculates the Odds Ratio
#' @param N         Number of Observations
#' @param J         Number of Assessment Items
#' @param K         Number of Attribute Levels as an `unsigned integer`.
#' @param Q         Q Matrix with dimensions \eqn{J x K}.
#' @param Y         Binary responses to assessements in \code{matrix} form with
#'                  dimensions \eqn{N \times J}{N x J}.
#' @param CLASS     Does the individual possess all the necessary attributes?
#' @param ss        A `vec` describing the probability of slipping or
#'                  the probability of an incorrect response for individuals
#'                  with all of the required attributes
#' @param gs        A `vec` describing the probability of guessing or
#'                  the probability subject correctly answers item \eqn{j} when
#'                  at least one attribute is lacking.
#' @param vj        A `vec` containing the powers of 2.
#' @param ETAmatnok A variant on the \eqn{\eta} Matrix.
#' @param a_by_q    Classification Matrix by a \eqn{Q} Matrix.
#' @param vv        Bijection vector with respect to \eqn{K}.
#' @details
#' No return is done here as the update is done by reference.
#' @noRd
NULL

#' Condition Threshold Mean
#'
#' Computes the conditional threshold mean
#' @param k         Present attribute level as `unsigned int`.
#' @param j         Present assessment items as `unsigned int`.
#' @param n_noks    Number of n okay observations?
#' @param N         Number of Assessment Items
#' @param K         Number of Observations
#' @param Yj        Number of Observations
#' @param CLASS     Does the individual possess all the necessary attributes?
#' @param Q         Q Matrix with dimensions \eqn{J x K}.
#' @param gj        The probability of guessing or the probability subject
#'                  correctly answers item \eqn{j} when at least one attribute
#'                  is lacking.
#' @param sj        The probability of slipping or the probability of an
#'                  incorrect response for individuals with all of the required
#'                  attributes
#' @param ETAmatnok A variant on the \eqn{\eta} matrix.
#' @return A `double` indicating the conditional threshold.
#' @noRd
NULL

#' Update the Parameters
#'
#' Perform a parameter update
#' @param N      Number of Observations
#' @param J      Number of Assessment Items
#' @param K      Number of Attribute Levels
#' @param nClass Number of classes?
#' @param Y      A `matrix` with dimensions \eqn{N \times J}{N x J} containing
#'               the binary responses to assessements.
#' @param ETA    Alpha profile matrix.
#' @param gs     A \code{vec} describing the probability of guessing or
#'               the probability subject correctly answers item \eqn{j} when at
#'               least one attribute is lacking.
#' @param ss     A \code{vec} describing the probability of slipping or
#'               the probability of an incorrect response for individuals with
#'               all of the required attributes
#' @param CLASS  Does the individual possess all the necessary attributes?
#'               (1 or 0)
#' @param pis    Latent Class Probabilities with length \eqn{K}
#' @details
#' gs, ss, CLASS, and pis are updated under this function.
#' @noRd
NULL

#' Generate a Random Q Matrix
#'
#' Creates a random Q matrix containing three identity matrices after
#' row permutation
#'
#' @param J An `int` that represents the number of items
#' @param K An `int` that represents the number of attributes/skills
#' @return A dichotomous `matrix` for Q.
#'
#' @examples
#' Q_matrix = random_Q(15, 4)
#' @export
random_Q <- function(J, K) {
    .Call(`_ecdm_random_Q`, J, K)
}

#' Verify Q Matrix is Identifiable
#'
#' Performs a check to see if Q is identifable or not.
#'
#' @param Q The Q matrix to be checked with dimensions \eqn{K \times J}{K x J}.
#'
#' @return A `bool` with value either: false or true
#' @export
check_identifiability <- function(Q) {
    .Call(`_ecdm_check_identifiability`, Q)
}

#' Generate the Attribute Matrix
#'
#' Creates an Attribute Matrix given Q
#'
#' @param Q A `matrix` with dimensions \eqn{J x K}
#'
#' @return A `matrix` with dimensions \eqn{2^K x K}, where \eqn{2^K = C}.
#' @export
#' @examples
#' q_rand = random_Q(13, 3)
#' a_mat = alpha_matrix(q_rand)
alpha_matrix <- function(Q) {
    .Call(`_ecdm_alpha_matrix`, Q)
}

#' Classification Matrix by Q Matrix
#'
#' Construct a classification matrix by Q Matrix
#' @param K Number of Attribute Levels as an `unsigned integer`.
#' @return A `mat`.
#' @export
ClassbyQmat <- function(K) {
    .Call(`_ecdm_ClassbyQmat`, K)
}

#' Simulate Binary Responses for DINA Model
#'
#' Simulation the Y Response for a DINA Model
#' @param N     Number of Observations
#' @param J     Number of Assessment Items
#' @param CLASS Does the individual possess all the necessary attributes?
#' @param ETA   \eqn{\eta} Matrix containing indicators.
#' @param gs    A `vec` describing the probability of guessing or
#'              the probability subject correctly answers item \eqn{j} when at
#'              least one attribute is lacking.
#' @param ss    A `vec` describing the probability of slipping or
#'              the probability of an incorrect response for individuals with
#'              all of the required attributes
#' @return A `mat`
#' @export
sim_Y_dina <- function(N, J, CLASS, ETA, gs, ss) {
    .Call(`_ecdm_sim_Y_dina`, N, J, CLASS, ETA, gs, ss)
}

#' Exploratory Determinatistic Input, Noise and Gate Model (EDINA)
#'
#' Compute the EDINA model
#' @inheritParams edina
#' @return
#' A `list` containing:
#' - **GS**: Guessing
#' - **SS**: Slipping
#' - **PIs**: Latent Class Probabilities with length \eqn{K}
#' - **QS**: Q matrix
#' - **ORs**: Odds Ratio
#' @noRd
edina_Gibbs_Q <- function(Y, K, burnin = 1000L, chain_length = 10000L) {
    .Call(`_ecdm_edina_Gibbs_Q`, Y, K, burnin, chain_length)
}

errum_Gibbs_Q <- function(Y, K, burnin, chain_length = 10000L) {
    .Call(`_ecdm_errum_Gibbs_Q`, Y, K, burnin, chain_length)
}

#' Simulate rRUM Data
#'
#' Generate data that falls underneath a rRUM modeling paradigm.
#'
#' @param N        Number of Subjects
#' @param J        Number of Assessment Items
#' @param K        Number of Attributes
#' @param rstar    Matrix of penalities for missing an attribute on an item
#'                 with dimensions \eqn{J \times K}{J x K}.
#' @param pistar   Vector of probabilities associated with whether
#'                 \eqn{Y_{ij} = 1} if subject \eqn{i} has all the required
#'                 attributes having length \eqn{J}.
#' @param Q        Matrix of attributes required for each assessment
#'                 item with dimensions \eqn{J \times K}{J x K}.
#' @param alpha    Matrix with dimensions \eqn{N \times K}{N x K} of 1s and 0s.
#' @export
simrRUM <- function(N, J, K, Q, rstar, pistar, alpha) {
    .Call(`_ecdm_simrRUM`, N, J, K, Q, rstar, pistar, alpha)
}

#' Parameter Update Routine for rRUM Gibbs Sampler
#'
#' @param N        Number of Subjects
#' @param J        Number of Assessment Items
#' @param K        Number of Attributes
#' @param C        Number of Classes (\eqn{2^K})
#' @param Y        Matrix of binary responses to assessment items with
#'                 dimensions \eqn{N \times J}{N x J}.
#' @param Q        Matrix of attributes required for each assessment
#'                 item with dimensions \eqn{J \times K}{J x K}.
#' @param alpha    Matrix with dimensions \eqn{N \times K}{N x K} of 1s and 0s.
#' @param X        Cube with dimensions \eqn{N \times J \times K}{N x J x K}.
#' @param Smat     Slipping parameters
#' @param Gmat     Guessing Parameters
#' @param pi       Vector of PIs
#' @param vv       Bijection vector of attributes
#' @param delta0   Vector of length \eqn{2^K} that corresponds to the
#'                 prior values for betas and dirichlet distributions of the
#'                 classes.
#' @export
parm_update <- function(N, J, K, C, Y, Q, alpha, X, Smat, Gmat, pi, vv, delta0) {
    .Call(`_ecdm_parm_update`, N, J, K, C, Y, Q, alpha, X, Smat, Gmat, pi, vv, delta0)
}

#' rRUM Gibbs-based Estimation
#'
#' Performs an estimation of the rRUM model using Gibbs sampling.
#'
#' @param Y            Matrix of binary responses to assessment items with
#'                     dimensions \eqn{N \times J}{N x J}.
#' @param Q            Matrix of attributes required for each assessment
#'                     item with dimensions \eqn{J \times K}{J x K}.
#' @param chain_length Number of iterations
#' @export
rRUM_Gibbs <- function(Y, Q, chain_length = 10000L) {
    .Call(`_ecdm_rRUM_Gibbs`, Y, Q, chain_length)
}

#' Update Parameters in Metropolis-Hastings Approach
#'
#' Helper functions that handles the process of updating the parameters
#' under the derving MH approach.
#'
#' @param N        Number of Subjects
#' @param J        Number of Assessment Items
#' @param K        Number of Attributes
#' @param C        Number of Classes (\eqn{2^K})
#' @param Y        Matrix of binary responses to assessment items with
#'                 dimensions \eqn{N \times J}{N x J}.
#' @param Q        Matrix of attributes required for each assessment
#'                 item with dimensions \eqn{J \times K}{J x K}.
#' @param alpha    Matrix with dimensions \eqn{N \times K}{N x K} of 1s and 0s.
#' @param pistar   Vector of probabilities associated with whether
#'                 \eqn{Y_{ij} = 1} if subject \eqn{i} has all the required
#'                 attributes having length \eqn{J}.
#' @param rstar    Matrix with dimensions \eqn{J \times K}{J x K}.
#' @param pi       Vector of length \eqn{2^K} containing the
#'                 latent class probabilities that \eqn{Y_{ij} = 1}.
#' @param vv       Bijection vector of length \eqn{k} for attributes.
#' @param delta0   Vector of length \eqn{2^K} that corresponds to the
#'                 prior values for betas and dirichlet distributions of the
#'                 classes.
#' @param delta    TBA?
#' @param Amat     TBA?
#' @export
parm_update_MH <- function(N, J, K, C, Y, Q, alpha, pistar, rstar, pi, vv, delta0, delta, Amat) {
    .Call(`_ecdm_parm_update_MH`, N, J, K, C, Y, Q, alpha, pistar, rstar, pi, vv, delta0, delta, Amat)
}

#' rRUM Metropolis-Hastings-based Estimation
#'
#' Performs an estimation of the rRUM model using the Metropolis-Hastings
#' derivation.
#'
#' @param Y            Matrix of binary responses to assessment items with
#'                     dimensions \eqn{N \times J}{N x J}.
#' @param Q            Matrix of attributes required for each assessment
#'                     item with dimensions \eqn{J \times K}{J x K}.
#' @param Amat         TBA?
#' @param delta        TBA?
#' @param chain_length Number of iterations
#' @return
#' A `list` containing:
#' - **PISTAR**: Estimates of the latent probability class.
#' - **RSTAR**: Estimates of the penalty parameter for missing a required
#'              \eqn{k}.
#' - **PIs**: Latent Class Probabilities with length \eqn{K}
#' - **ACCEPTREJECT_PISTAR**: Vector of 1's or 0's indicating whether the
#'   values for pistar was accepted or rejected.
#' - **ACCEPTREJECT_RSTAR**: Vector of 1's or 0's indicating whether the
#'   values for rstar was accepted or rejected.
#' @export
rRUM_MH <- function(Y, Q, Amat, delta, chain_length = 10000L) {
    .Call(`_ecdm_rRUM_MH`, Y, Q, Amat, delta, chain_length)
}

#' Compute the Odds Ratio
#'
#' Calculates the Odds Ratio
#' @param N  Number of Observations
#' @param J  Number of Assessment Items
#' @param Yt Estimated binary responses to assessements in \code{matrix} form
#'           with dimensions \eqn{N \times J}{N x J}.
#' @return A `matrix` with dimensions \eqn{J \times J}{J x J}.
#' @export
OddsRatio <- function(N, J, Yt) {
    .Call(`_ecdm_OddsRatio`, N, J, Yt)
}

#' Bijection Vector
#'
#' @param K number of levels
#' @return A \code{vec} with length \eqn{K}.
#' @export
bijectionvector <- function(K) {
    .Call(`_ecdm_bijectionvector`, K)
}

#' Inverse Bijection Vector
#'
#' @param CL A \code{double} that controls ...
#' @inheritParams bijectionvector
#' @return A \code{vec} with length \eqn{K}.
#' @export
inv_bijectionvector <- function(K, CL) {
    .Call(`_ecdm_inv_bijectionvector`, K, CL)
}

